name: "Refresh Gitee Pages"
description: "Auto Refresh Gitee Pages"
icon: "refresh-ccw"
inputs:
  repository:
    description: "The repository, Like 'Mizuka/Mizuka'"
    required: true
    default: "World"
  cookie:
    description: "Gitee Cookie"
    required: true
    default: ""
  branch:
    description: "Which branch to build"
    default: "master"
    required: false
  directory:
    description: "Which directory to build"
    default: ""
    required: false
  https:
    description: "Use Force Https?"
    default: true
    required: false
outputs:
  result: # id of output
    description: "The result of api"
runs:
  using: "node12"
  main: "dist/index.js"
